# Site settings
title: Sangam
description: Hello 
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://sangamkhanal.com.np/" # the base hostname & protocol for your site, e.g. http://example.com

# Banner Section
hero: 112.jpg
hero-title: Welcome to My Blog
hero-description: Working on Drug Discovery and Fluid Mechanics

# Author - Creator
author-name: Sangam Khanal
author-image: sangam.jpg
about-author: My name is Sangam Khanal. I am a computer engineer and I love.. well computers.
author-email: mail@sangamkhanal.com.np 
author-facebook: https://twitter.com/
author-instagram: https://www.instagram.com/

# Social Media Links (Links are located in hero and footer)
facebook: https://facebook.com/me.chinge
instagram: https://www.instagram.com/_chinge_

# Contact Form Settings
contact-subtitle: Please leave your message here # Title for the subscription form.

# Google Analytics
google-analytics: UA-200613185-1 # Add your identifier. For example UA-99631805-1.

# Newsletter
mailchimp: # Add your MailChimp form identifier. For example - blogenjoyfreedom.us16.list-manage.com/subscribe/post?u=cd56155d76ddeeb4c0bc4d080&amp;id=7a526cd13e

# Comment Section (Disqus)
disqus-identifier: chinge # Add your shortname for Disqus Comment. For example mr-brown

# Build settings
markdown: kramdown
permalink: pretty
paginate: 9
paginate_path: "/page/:num"

# Pages path
defaults:
  - scope:
      path: '_pages'
    values:
      permalink: /:basename:output_ext

plugins:
  - jekyll-paginate
  - jekyll-feed

include:
  - _pages

# Exclude from processing.
exclude:
 - Gemfile
 - Gemfile.lock
 - vendor
